### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by mato-gallardo** [awslabs/amazon-qldb-driver-nodejs#338] opened 2023-02-10 18:45 UTC
Dear AWS QLDB team: 
We've been running into a problem with QLDB where it's returning an "InternalFailure: UnknownError" with some regularity. In the past month the problem has occurred 21 times. We managed to trace the error as far back as [the error handler in the AWS SDK](https://github.com/aws/aws-sdk-js-v3/blob/8fdd7a510875e7ca77d025ef5a9e5d9ab9ac38dd/clients/client-qldb-session/src/protocols/Aws_json1_0.ts#L77) but passed that we have no insight as the error seems to be getting thrown by the actual QLDB service itself.
It would be great if we could somehow stop these errors from occurring.

Example of trace we get back:
 `InternalFailure: UnknownError
    at throwDefaultError (/usr/src/app/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_0SendCommandCommandError (/usr/src/app/node_modules/@aws-sdk/client-qldb-session/dist-cjs/protocols/Aws_json1_0.js:59:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /usr/src/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async StandardRetryStrategy.retry (/usr/src/app/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /usr/src/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22`

link: https://github.com/aws/aws-sdk-js-v3/blob/8fdd7a510875e7ca77d025ef5a9e5d9ab9ac38dd/clients/client-qldb-session/src/protocols/Aws_json1_0.ts

**Comment by bwinchester** [comment] 2023-02-10 21:28
👋 @mato-gallardo ,

Sorry this is happening. Would love to help you. Can you open a ticket through https://aws.amazon.com/contact-us/ and give us some details on your account, region, ledger name, and as many of the transactionIDs as you have with these 21 errors? The info will help us investigate what is going on.

**Comment by eikeon** [comment] 2023-02-22 19:26
We have recently started seeing these as well. Not sure if they started after we switched to 3.x or more recently. But have seen hundreds of them in the last couple days on relatively small workloads. @mato-gallardo did you get any resolution on this issue?

**Comment by eikeon** [comment] 2023-02-22 19:39
Looking at our package-lock.json file... we're running w/ 
```
"@aws-sdk/client-qldb-session": {
            "version": "3.258.0",
```

and the driver has 

```
"requires": {
                "@aws-sdk/client-qldb-session": "^3.195.0",
```

if it's related to some regression in a newer version of `@aws-sdk/client-qldb-session`

**Comment by bwinchester** [comment] 2023-02-22 19:53
> We have recently started seeing these as well. Not sure if they started after we switched to 3.x or more recently. But have seen hundreds of them in the last couple days on relatively small workloads. @mato-gallardo did you get any resolution on this issue?

@eikeon Can you open a support ticket with sessionIds and transactionIds from what you are seeing. https://aws.amazon.com/contact-us/

**Comment by mato-gallardo** [comment] 2023-02-22 19:57
yup, I've opened one case and sent the transactionIds. I can not post the data here (sorry).

**Comment by mato-gallardo** [comment] 2023-02-22 20:03
@eikon AWS has the data and they working on it.  We are also using the last version.

**Comment by gxxcastillo** [comment] 2023-03-05 07:44
Not sure if it's related but I'm consistently seeing this error: 
```
 Cannot find module '@aws-sdk/client-qldb'\nRequire stack:\n- /var/task/node_modules/amazon-qldb-driver-nodejs/dist/src/errors/Errors.js\n- /var/task/node_modules/amazon-qldb-driver-nodejs/dist/index.js\n- /var/task/c8ledger/index.js\n- /var/task/services/transferViaC8Ledger.js\n- /var/task/handlers/submitPayment.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js
```

**Comment by butleragrant** [comment] 2023-03-13 20:28
Closing this issue as we are continuing with the investigation internally. The driver should retry these errors and due to their transient nature, retries generally should succeed. In the meantime, apologies for the noise in logs.

@gxxcastillo your issue appears to be unrelated, feel free to open a new issue if you are having trouble.

**Closed as completed by butleragrant** 2023-03-13 20:28 UTC

**Comment by eikeon** [comment] 2023-03-14 00:50
@butleragrant The driver appears to not be retrying these errors nor are the retries succeeding, if it is. As such, this issue is more than noise in our logs.  @mato-gallardo how are you doing w/ this issue? Are you able to get past it with enough retries?

**Comment by mato-gallardo** [comment] 2023-03-14 00:54
Yup, the retries get the job done.

**Comment by eikeon** [comment] 2023-03-14 01:18
@mato-gallardo Thank you. 

Checking my retry config now... which I'm passing in as the fifth argument to the QLDBDriver constructor. I'm also seeing the type for the second argument is showing a couple retry related bits. Perhaps I need to specify those too. /me looks at documentation / source again.
